spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/Agency}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.security: DEBUG


app:
  image-dir: ${IMAGE_DIR:/Users/kuldeepchauhan1111/Harsh/Projects/src/main/resources/images/}
  image-base-url: ${IMAGE_BASE_URL:http://localhost:8080/images/}