spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/Agency}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Harsh@2804}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.security: DEBUG

app:
  image-dir: ${IMAGE_DIR:D:\\Agency Project\\Agency\\Agency\\src\\main\\resources\\images\\}
  image-base-url: ${IMAGE_BASE_URL:http://localhost:8080/images/}

#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/Agency
#    username: root
#    password: Harsh@2804
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#    ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#
#server:
#  port: 8082
#
#logging:
#  level:
#    org.springframework.security: DEBUG